SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE `school_type` (
  `id` int(11) NOT NULL,
  `Ownership` varchar(50) NOT NULL,
  `Town` varchar(100) NOT NULL,
  `school_id` int(11) NOT NULL,
  `contact` varchar(12) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `school_type` (`id`, `Ownership`, `Town`, `school_id`, `contact`) VALUES
(1, 'Public', 'Diobu', 1, '09150738754');


ALTER TABLE `school_type`
  ADD PRIMARY KEY (`id`),
  ADD KEY `school_id` (`school_id`);


ALTER TABLE `school_type`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;


ALTER TABLE `school_type`
  ADD CONSTRAINT `school_type_ibfk_1` FOREIGN KEY (`school_id`) REFERENCES `schoolfinder` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
